# Generated by Django 5.0.6 on 2024-06-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
    ]
