# Generated by Django 5.0.6 on 2024-06-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('balance_after_transaction', models.DecimalField(decimal_places=3, max_digits=8)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Borrowed'), (3, 'Returned')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userlibraryaccountmodel')),
            ],
        ),
    ]
