# Generated by Django 5.0.6 on 2024-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
