# Generated by Django 5.0.6 on 2024-06-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrow_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='books',
            new_name='book',
        ),
    ]
